Update quote to 1.0.9
mobilecoinofficial/rust-mbedtls pull request #89
Opened 2023-03-07 02:10 UTC by samdealy

2023-03-07 16:30 UTC, jcape requested changes
This is actually downgrading quote, is something specifying `quote =  "=1.0.9"` somewhere?

2023-03-08 08:34 UTC, jcape requested changes

2023-03-08 08:34 UTC, jcape commented on .gitignore
> +.idea/
```suggestion
```

2023-03-08 18:52 UTC, samdealy commented
> This is actually downgrading quote, is something specifying `quote = "=1.0.9"` somewhere?

This is no longer the case (for posterity).

2023-03-09 18:21 UTC, jcape approved these changes

2023-03-09 18:28 UTC, nick-mobilecoin approved these changes

2023-03-10 17:40 UTC, jcape requested changes
Please remove `.idea` from `.gitignore`, and use the global ignore.

2023-03-10 19:43 UTC, jcape approved these changes

2023-03-10 20:25 UTC, merged