modify license expressions in cargo toml
mobilecoinofficial/rust-mbedtls pull request #98
Opened 2023-03-25 23:51 UTC by cbeck88

cargo deny doesn't seem to understand `GPL-2.0+` right now, see https://github.com/EmbarkStudios/cargo-deny/issues/498

2023-03-29 12:15 UTC, jcape approved these changes

2023-03-29 12:16 UTC, jcape requested changes
Sorry, spoke too soon: https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields

2023-03-29 12:16 UTC, jcape commented on mbedtls-sys/Cargo.toml
> +license = "Apache-2.0/GPL-2.0-or-later"
```suggestion
license = "Apache-2.0 OR GPL-2.0-or-later"
```

2023-03-29 12:16 UTC, jcape commented on mbedtls/Cargo.toml
> +license = "Apache-2.0/GPL-2.0-or-later"
```suggestion
license = "Apache-2.0 OR GPL-2.0-or-later"
```

2023-03-29 17:12 UTC, jcape approved these changes

2023-03-30 00:35 UTC, varsha888 approved these changes

2023-03-30 00:35 UTC, merged